// Auto-installer: generates integration credentials, stores them in the database
// and installs the generated config files into the organization's native website.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const json = (status: number, body: unknown) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

async function sha256Hex(s: string) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(buf)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
function randomToken(bytes = 32) {
  const arr = new Uint8Array(bytes);
  crypto.getRandomValues(arr);
  return Array.from(arr).map((b) => b.toString(16).padStart(2, "0")).join("");
}

interface InstalledFile { path: string; content: string; bytes: number }

function buildFiles(opts: {
  orgId: string; slug: string; name: string; apiKeyPlain: string; prefix: string;
  environment: string; scopes: string[]; siteUrl: string | null;
}): InstalledFile[] {
  const config = {
    generated_at: new Date().toISOString(),
    platform: "FYSORA FASHN",
    org_id: opts.orgId,
    org_slug: opts.slug,
    org_name: opts.name,
    environment: opts.environment,
    api_base: `${SUPABASE_URL}/functions/v1`,
    api_key_prefix: opts.prefix,
    scopes: opts.scopes,
    website_url: opts.siteUrl,
    endpoints: {
      catalogue: `${SUPABASE_URL}/functions/v1/embed-widget?org=${opts.slug}`,
      submit_order: `${SUPABASE_URL}/functions/v1/submit-cart-order`,
      verify: `${SUPABASE_URL}/functions/v1/verify-org-integration`,
    },
  };

  const runtime = `/* FYSORA FASHN integration — auto-installed ${config.generated_at}
   Organization: ${opts.name} (${opts.slug})
   Do not edit by hand: regenerated by the integration auto-installer. */
(function () {
  var FYSORA = {
    orgId: ${JSON.stringify(opts.orgId)},
    orgSlug: ${JSON.stringify(opts.slug)},
    environment: ${JSON.stringify(opts.environment)},
    apiBase: ${JSON.stringify(config.api_base)},
    apiKey: ${JSON.stringify(opts.apiKeyPlain)},
    request: function (path, options) {
      options = options || {};
      var headers = Object.assign(
        { "Content-Type": "application/json", "X-Api-Key": FYSORA.apiKey, "X-Org-Id": FYSORA.orgId },
        options.headers || {}
      );
      return fetch(FYSORA.apiBase + path, Object.assign({}, options, { headers: headers }));
    }
  };
  window.FYSORA_INTEGRATION = FYSORA;
})();
`;

  const env = [
    `# FYSORA FASHN integration — auto-installed ${config.generated_at}`,
    `FYSORA_ORG_ID=${opts.orgId}`,
    `FYSORA_ORG_SLUG=${opts.slug}`,
    `FYSORA_ENVIRONMENT=${opts.environment}`,
    `FYSORA_API_BASE=${config.api_base}`,
    `FYSORA_API_KEY=${opts.apiKeyPlain}`,
    "",
  ].join("\n");

  const files = [
    { path: "public/fysora-integration.json", content: JSON.stringify(config, null, 2) },
    { path: "public/fysora-integration.js", content: runtime },
    { path: ".env.fysora", content: env },
  ];
  return files.map((f) => ({ ...f, bytes: new TextEncoder().encode(f.content).length }));
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") return json(405, { ok: false, error: "Method not allowed" });

  const authHeader = req.headers.get("Authorization");
  if (!authHeader?.startsWith("Bearer ")) return json(401, { ok: false, error: "Unauthorized" });

  const userClient = createClient(SUPABASE_URL, ANON_KEY, { global: { headers: { Authorization: authHeader } } });
  const admin = createClient(SUPABASE_URL, SERVICE_ROLE);

  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData?.user) return json(401, { ok: false, error: "Invalid session" });
  const userId = userData.user.id;

  let body: Record<string, unknown>;
  try { body = await req.json(); } catch { return json(400, { ok: false, error: "Invalid JSON" }); }

  const action = String(body.action ?? "install");
  const { data: isSuper } = await admin.rpc("has_role", { _user_id: userId, _role: "super_admin" });

  let orgIds: string[] = [];
  if (action === "install_all") {
    if (!isSuper) return json(403, { ok: false, error: "super_admin required for bulk install" });
    const { data: sites } = await admin.from("org_websites").select("org_id").eq("is_enabled", true);
    orgIds = (sites ?? []).map((s: { org_id: string }) => s.org_id);
  } else if (action === "install") {
    const orgId = String(body.org_id ?? "");
    if (!orgId) return json(400, { ok: false, error: "org_id required" });
    const { data: isAdmin } = await admin.rpc("is_org_admin", { _user_id: userId, _org_id: orgId });
    if (!isSuper && !isAdmin) return json(403, { ok: false, error: "Forbidden" });
    orgIds = [orgId];
  } else {
    return json(400, { ok: false, error: `Unknown action: ${action}` });
  }

  const environment = body.environment === "test" ? "test" : "live";
  const scopes: string[] = Array.isArray(body.scopes) && (body.scopes as string[]).length
    ? (body.scopes as string[]).slice(0, 12)
    : ["catalogue:read", "orders:write"];

  const results: Array<Record<string, unknown>> = [];

  for (const orgId of orgIds) {
    try {
      const { data: org } = await admin.from("organizations").select("id, name, slug").eq("id", orgId).maybeSingle();
      if (!org) { results.push({ org_id: orgId, ok: false, error: "Organization not found" }); continue; }

      const { data: site } = await admin
        .from("org_websites")
        .select("public_website_url, webhook_url, mode")
        .eq("org_id", orgId).maybeSingle();

      // 1. Generate credentials
      const raw = randomToken(32);
      const prefix = `fsa_${environment}_${raw.slice(0, 8)}`;
      const plaintext = `${prefix}_${raw.slice(8)}`;
      const keyHash = await sha256Hex(plaintext);
      const apiSecret = `whsec_${randomToken(24)}`;

      // 2. Persist the hashed key
      const { data: keyRow, error: keyErr } = await admin.from("org_integration_api_keys").insert({
        org_id: orgId,
        name: String(body.name ?? `${org.name} website integration`).slice(0, 80),
        key_prefix: prefix, key_hash: keyHash, scopes, environment, created_by: userId,
      }).select("id, name, key_prefix, scopes, environment, created_at").single();
      if (keyErr) throw keyErr;

      // 3. Persist usable credentials for the org's website (admin-only table)
      const { error: secErr } = await admin.from("org_website_secrets").upsert({
        org_id: orgId, api_key: plaintext, api_secret: apiSecret, updated_at: new Date().toISOString(),
      }, { onConflict: "org_id" });
      if (secErr) throw secErr;

      // 4. Build + install the integration files into the native website
      const files = buildFiles({
        orgId, slug: org.slug, name: org.name, apiKeyPlain: plaintext, prefix, environment,
        scopes, siteUrl: site?.public_website_url ?? site?.webhook_url ?? null,
      });

      await admin.from("org_website_integration_installs")
        .update({ status: "superseded" }).eq("org_id", orgId).eq("status", "installed");

      const target = site?.mode === "custom_integration" ? "github_pages" : "native_website";
      const { data: install, error: instErr } = await admin
        .from("org_website_integration_installs").insert({
          org_id: orgId, api_key_id: keyRow.id, key_prefix: prefix, environment,
          target, files, status: "installed", installed_by: userId,
        }).select("id, installed_at, target").single();
      if (instErr) throw instErr;

      // 5. Queue a deployment so externally hosted sites pick the files up
      if (target === "github_pages") {
        await admin.from("deployment_jobs").insert({
          org_id: orgId, kind: "github_push", created_by: userId,
          payload: { reason: "integration_key_install", install_id: install.id, files },
        });
      }

      await admin.from("audit_logs").insert({
        user_id: userId, action: "integration_keys_auto_installed",
        entity_type: "org_website_integration_install", entity_id: install.id,
        metadata: { org_id: orgId, key_prefix: prefix, environment, target, file_count: files.length },
      });

      results.push({
        org_id: orgId, org_name: org.name, ok: true,
        install_id: install.id, target: install.target, installed_at: install.installed_at,
        key: keyRow, api_key: plaintext, api_secret: apiSecret,
        files: files.map((f) => ({ path: f.path, bytes: f.bytes })),
      });
    } catch (e) {
      const message = (e as Error).message;
      await admin.from("org_website_integration_installs").insert({
        org_id: orgId, key_prefix: "n/a", environment, status: "failed",
        error: message.slice(0, 500), installed_by: userId,
      });
      results.push({ org_id: orgId, ok: false, error: message });
    }
  }

  const failed = results.filter((r) => !r.ok).length;
  return json(failed > 0 && failed === results.length ? 400 : 200, {
    ok: failed === 0,
    installed: results.length - failed,
    failed,
    results,
    notice: "Plaintext keys are shown once here and stored in the organization's website secrets.",
  });
});
